### ISSUE TITLE
NumberFormatException when deserializing a 128-bit integer

### ISSUE THREAD

**Issue by rwalbergpd** [com-lihaoyi/upickle#240]
Using `"com.lihaoyi" %% "ujson" % "0.6.6"`

```
val json = ujson.read("{'foo': 28291041994989161181883157038606177750}")
```

yields:

```
28291041994989161181883157038606177750
java.lang.NumberFormatException: 28291041994989161181883157038606177750
	at ujson.util.Util$.parseLong(Util.scala:57)
	at ujson.util.Util$.parseIntegralNum(Util.scala:23)
	at ujson.Js$.visitNum(Js.scala:181)
	at ujson.Js$.visitNum(Js.scala:77)
	at ujson.Parser.parseNum(Parser.scala:171)
	at ujson.Parser.rparse(Parser.scala:404)
	at ujson.Parser.parse(Parser.scala:330)
	at ujson.Parser.parse(Parser.scala:325)
	at ujson.SyncParser.parse(SyncParser.scala:23)
	at ujson.StringParser$.transform(StringParser.scala:28)
	at ujson.StringParser$.transform(StringParser.scala:27)
	at ujson.Transformable$fromTransformer.transform(Transformable.scala:13)
	at ujson.package$.transform(package.scala:2)
	at ujson.package$.read(package.scala:4)
```

**Comment by htmldoug** [comment]
Looks like this just affects ujson's AST. Workaround: the http://www.lihaoyi.com/upickle/#OtherASTs probably handle it properly. I know play-json represents all numbers as `BigDecimal`.

https://tools.ietf.org/html/rfc8259#section-6 and https://tools.ietf.org/html/rfc8259#section-9 indicate that parsers may reject large numbers, although [all other implementations on JSONTestSuite](https://raw.githubusercontent.com/nst/JSONTestSuite/master/results/pruned_results.png) handle them. This limitation would be surprising.

Out of curiosity, I ran ujson through https://github.com/nst/JSONTestSuite/commit/5b47b778b9a2b87007fe6500b6c919737c46008d. Here are the results (excluding expected passes/rejections):

![jsontestsuite](https://user-images.githubusercontent.com/663139/44447083-09fc6680-a5b5-11e8-94b7-530f6dc67e5a.png)

**Comment by htmldoug** [comment]
Would be nice for @lihaoyi to weigh in. If this limitation is intentional, seems to me like it should be documented somewhere.

**Comment by julienrf** [comment]
It seems to me that the ujson AST is not correct. Would it be possible to fix it rather than suggesting to switch to an alternative AST?

**Comment by lihaoyi** [comment]
This seems like a parser issue, nothing to do with the AST

**Comment by julienrf** [comment]
I might be wrong but it seems to me that the only way to represent JSON numbers in the AST is to use [`ujson.Num`](https://javadoc.io/doc/com.lihaoyi/ujson_2.13/latest/ujson/Num.html), which only supports `Double` values. Am I missing something?

It seems that the parser already has a `visitFloat64String`.

**Comment by lihaoyi** [comment]
The uJson AST is designed to mimic the Javascript AST, which takes only numbers. If you want something else, use a different AST (or don’t use an AST, like uPickle)

**Comment by lihaoyi** [comment]
Note that unlike other JSON libraries, ujson.Value isn’t blessed in any way, so if you use a uJson with a different AST you need not worry about ujson.Value tradeoffs at all. In fact, internally uPickle defines its own IndexedValue AST for cases where we need the source indices and non-lossy temporary storage of the incoming JSON, so don’t feel bad about defining your own AST for your own use case

**Comment by julienrf** [comment]
Thanks for the clarification!

**Comment by lihaoyi** [comment]
This still occurs on latest master

```scala
scala> ujson.read("28291041994989161181883157038606177750")
ujson.read("28291041994989161181883157038606177750")java.lang.NumberFormatException: 28291041994989161181883157038606177750
  at upickle.core.CharUtils$.parseLong(CharUtils.scala:177)
  at upickle.core.CharUtils$.parseIntegralNum(CharUtils.scala:128)
  at upickle.core.ParseUtils$.parseIntegralNum(ParseUtils.scala:29)
  at ujson.Value$.visitFloat64StringParts(Value.scala:184)
  at ujson.Value$.visitFloat64StringParts(Value.scala:126)
  at upickle.core.Visitor.visitFloat64CharParts(Visitor.scala:62)
  at upickle.core.Visitor.visitFloat64CharParts$(Visitor.scala:61)
  at ujson.Value$.visitFloat64CharParts(Value.scala:126)
  at ujson.CharParser.visitFloat64StringPartsWithWrapper(CharParser.scala:176)
  at ujson.CharParser.parseNumTopLevel(CharParser.scala:216)
  at ujson.CharParser.parseTopLevel0(CharParser.scala:342)
  at ujson.CharParser.parseTopLevel(CharParser.scala:323)
  at ujson.CharParser.parse(CharParser.scala:72)
  at ujson.StringParser$.transform(StringParser.scala:28)
  at ujson.StringParser$.transform(StringParser.scala:27)
  at ujson.Readable$fromTransformer.transform(Readable.scala:16)
  at ujson.package$.transform(package.scala:4)
  at ujson.package$.$anonfun1(package.scala:10)
  at upickle.core.TraceVisitor$.withTrace(TraceVisitor.scala:18)
  at ujson.package$.read(package.scala:10)
  ... 32 elided
```

The basic problem appears to be that we are using a `parseLong` fast-path inside `ujson.Value.visitFloat64StringParts`. This is only valid for numbers of a certain digit-length. We should be checking for numbers larger than that length, and falling back to the `toDouble` slow path for thoser
