### ISSUE TITLE
ujson 1.0.0 is incompatible with java 1.8

### ISSUE THREAD

**Issue by OlegYch** [com-lihaoyi/upickle#310]
```
new ujson.ByteBufferParser(java.nio.ByteBuffer.wrap("{}".toCharArray.map(_.toByte))).parse(new ujson.BytesRenderer())
```
throws 
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
  at ujson.ByteBufferParser.close(ByteBufferParser.scala:26)
  at ujson.Parser.parse(Parser.scala:114)
  ... 33 elided
```
(found with sbt-missinglink)

**Comment by lihaoyi** [comment]
Should be fixed in the latest version I think, now that we're publishing from CI

**Comment by OlegYch** [comment]
yep, newer versions work fine, thanks
